spring.application.name=incubyte-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/Sweet-corner
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
